// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniGate.Infrastructure;

#nullable disable

namespace UniGate.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UniGate.Core.Entities.Admission", b =>
                {
                    b.Property<int>("AdmissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<int>("MajorID")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaxScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("MedianScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("MinScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Percentile25")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Percentile75")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("UniversityID")
                        .HasColumnType("int");

                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.HasKey("AdmissionID");

                    b.HasIndex("GroupID");

                    b.HasIndex("MajorID");

                    b.HasIndex("UniversityID");

                    b.ToTable("Admissions");
                });

            modelBuilder.Entity("UniGate.Core.Entities.CareerSuggestion", b =>
                {
                    b.Property<int>("SuggestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("MajorID")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ResultCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("TestTypeID")
                        .HasColumnType("int");

                    b.HasKey("SuggestionID");

                    b.HasIndex("MajorID");

                    b.HasIndex("TestTypeID");

                    b.ToTable("CareerSuggestions");
                });

            modelBuilder.Entity("UniGate.Core.Entities.GroupScoreDistribution", b =>
                {
                    b.Property<int>("DistDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CountStudents")
                        .HasColumnType("int");

                    b.Property<short>("ExamYear")
                        .HasColumnType("smallint");

                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<decimal>("ProbDistribution")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("TotalScoreLevel")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("DistDetailID");

                    b.HasIndex("GroupID");

                    b.ToTable("GroupScoreDistributions");
                });

            modelBuilder.Entity("UniGate.Core.Entities.Major", b =>
                {
                    b.Property<int>("MajorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("MajorCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MajorName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("MajorID");

                    b.ToTable("Majors");
                });

            modelBuilder.Entity("UniGate.Core.Entities.MajorGroup", b =>
                {
                    b.Property<int>("MajorGroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<short?>("ExamYear")
                        .HasColumnType("smallint");

                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<int>("MajorID")
                        .HasColumnType("int");

                    b.HasKey("MajorGroupID");

                    b.HasIndex("GroupID");

                    b.HasIndex("MajorID");

                    b.ToTable("MajorGroups");
                });

            modelBuilder.Entity("UniGate.Core.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("TokenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TokenCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("TokenID");

                    b.HasIndex("UserID");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("UniGate.Core.Entities.Question", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CorrectOption")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("OptionA")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("OptionB")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("OptionC")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("OptionD")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("TestTypeID")
                        .HasColumnType("int");

                    b.HasKey("QuestionID");

                    b.HasIndex("TestTypeID");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("UniGate.Core.Entities.Region", b =>
                {
                    b.Property<int>("RegionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("BonusScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RegionID");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("UniGate.Core.Entities.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("UniGate.Core.Entities.ScoreConversion", b =>
                {
                    b.Property<int>("ConversionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CertificateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("ConvertedScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<short?>("ExamYear")
                        .HasColumnType("smallint");

                    b.Property<decimal>("OriginalScore")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ConversionID");

                    b.ToTable("ScoreConversions");
                });

            modelBuilder.Entity("UniGate.Core.Entities.SubjectGroup", b =>
                {
                    b.Property<int>("GroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Subjects")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("GroupID");

                    b.HasIndex("GroupName")
                        .IsUnique();

                    b.ToTable("SubjectGroups");
                });

            modelBuilder.Entity("UniGate.Core.Entities.TestResult", b =>
                {
                    b.Property<int>("ResultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ResultCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ResultText")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("TestDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TestTypeID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ResultID");

                    b.HasIndex("TestTypeID");

                    b.HasIndex("UserID");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("UniGate.Core.Entities.TestType", b =>
                {
                    b.Property<int>("TestTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("TestTypeID");

                    b.HasIndex("TestName")
                        .IsUnique();

                    b.ToTable("TestTypes");
                });

            modelBuilder.Entity("UniGate.Core.Entities.University", b =>
                {
                    b.Property<int>("UniversityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UniversityCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("UniversityName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("UniversityID");

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("UniGate.Core.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("RegionID")
                        .HasColumnType("int");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RegionID");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UniGate.Core.Entities.UserAnswer", b =>
                {
                    b.Property<int>("AnswerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AnswerDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.Property<string>("SelectedOption")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("AnswerID");

                    b.HasIndex("QuestionID");

                    b.HasIndex("UserID");

                    b.ToTable("UserAnswers");
                });

            modelBuilder.Entity("UniGate.Core.Entities.UserScore", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<decimal?>("DiemCongThem")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("DoiTuong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("HB_Anh_10")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("HB_Anh_11")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("HB_Anh_12")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("HB_Toan_10")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("HB_Toan_11")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("HB_Toan_12")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("HB_Van_10")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("HB_Van_11")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("HB_Van_12")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("KhuVuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Thpt_Anh")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Thpt_Toan")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Thpt_Van")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("UserID");

                    b.ToTable("UserScores");
                });

            modelBuilder.Entity("UniGate.Core.Entities.UserSelectedCombo", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.HasKey("UserID", "GroupID");

                    b.HasIndex("GroupID");

                    b.ToTable("UserSelectedCombos");
                });

            modelBuilder.Entity("UniGate.Core.Entities.Admission", b =>
                {
                    b.HasOne("UniGate.Core.Entities.SubjectGroup", "SubjectGroup")
                        .WithMany()
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniGate.Core.Entities.Major", "Major")
                        .WithMany()
                        .HasForeignKey("MajorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniGate.Core.Entities.University", "University")
                        .WithMany()
                        .HasForeignKey("UniversityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");

                    b.Navigation("SubjectGroup");

                    b.Navigation("University");
                });

            modelBuilder.Entity("UniGate.Core.Entities.CareerSuggestion", b =>
                {
                    b.HasOne("UniGate.Core.Entities.Major", "Major")
                        .WithMany()
                        .HasForeignKey("MajorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniGate.Core.Entities.TestType", "TestType")
                        .WithMany()
                        .HasForeignKey("TestTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");

                    b.Navigation("TestType");
                });

            modelBuilder.Entity("UniGate.Core.Entities.GroupScoreDistribution", b =>
                {
                    b.HasOne("UniGate.Core.Entities.SubjectGroup", "SubjectGroup")
                        .WithMany()
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubjectGroup");
                });

            modelBuilder.Entity("UniGate.Core.Entities.MajorGroup", b =>
                {
                    b.HasOne("UniGate.Core.Entities.SubjectGroup", "SubjectGroup")
                        .WithMany()
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniGate.Core.Entities.Major", "Major")
                        .WithMany()
                        .HasForeignKey("MajorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");

                    b.Navigation("SubjectGroup");
                });

            modelBuilder.Entity("UniGate.Core.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("UniGate.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniGate.Core.Entities.Question", b =>
                {
                    b.HasOne("UniGate.Core.Entities.TestType", "TestType")
                        .WithMany()
                        .HasForeignKey("TestTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestType");
                });

            modelBuilder.Entity("UniGate.Core.Entities.TestResult", b =>
                {
                    b.HasOne("UniGate.Core.Entities.TestType", "TestType")
                        .WithMany()
                        .HasForeignKey("TestTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniGate.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniGate.Core.Entities.User", b =>
                {
                    b.HasOne("UniGate.Core.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionID");

                    b.HasOne("UniGate.Core.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("UniGate.Core.Entities.UserAnswer", b =>
                {
                    b.HasOne("UniGate.Core.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniGate.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniGate.Core.Entities.UserScore", b =>
                {
                    b.HasOne("UniGate.Core.Entities.User", "User")
                        .WithOne("UserScore")
                        .HasForeignKey("UniGate.Core.Entities.UserScore", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniGate.Core.Entities.UserSelectedCombo", b =>
                {
                    b.HasOne("UniGate.Core.Entities.SubjectGroup", "SubjectGroup")
                        .WithMany()
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniGate.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubjectGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniGate.Core.Entities.User", b =>
                {
                    b.Navigation("UserScore");
                });
#pragma warning restore 612, 618
        }
    }
}
